version: '0.2'
services:
  database:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./server
    env_file:
      - .env
    ports:
      - '8080:8080'
    depends_on:
      - database

  frontend:
    build:
      context: ./client
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://api:8080
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  mysql_data:
