name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # or whatever version you're using

      - name: Install Dependencies
        run: npm install # or `yarn install` if you're using yarn

      - name: Build App
        run: npm run build # make sure this command exists in your package.json


      # - name: Run Tests
      #  run: npm run test # optional, remove if not needed
